### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by 4crash** [applegrew/django-select2#449]
This error message occured while I tried to install django-select2. 
Probably now have set czech coding charset-1250 in python.

I have no problems with other django packages.

File "C:\Program Files\Python36\lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 863: character maps to <undefined>
    error in setup command: Error parsing C:\Users\crash\AppData\Local\Temp\pip-build-m_0efxap\Django-Select2\setup.cfg: UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 863: character maps to <undefined>

Please, can you help me solve it?
Thanks 
Tomas

**Comment by jieter** [comment]
I also get this error while installing django-select2 in our docker image used for CI.

Using tox it installs fine on python 2.7, but fails on python 3.6 with this stack trace:
```
Collecting django-select2==6.0.0 (from -r /opt/atlassian/pipelines/agent/build/requirements.txt (line 30))
  Using cached django-select2-6.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-build-_vhx9u12/django-select2/.eggs/pbr-3.1.1-py3.6.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-build-_vhx9u12/django-select2/.eggs/pbr-3.1.1-py3.6.egg/pbr/util.py", line 249, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-build-_vhx9u12/django-select2/.eggs/pbr-3.1.1-py3.6.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-build-_vhx9u12/django-select2/.eggs/pbr-3.1.1-py3.6.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-build-_vhx9u12/django-select2/.eggs/pbr-3.1.1-py3.6.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-build-_vhx9u12/django-select2/.eggs/pbr-3.1.1-py3.6.egg/pbr/packaging.py", line 737, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "/tmp/pip-build-_vhx9u12/django-select2/.eggs/pbr-3.1.1-py3.6.egg/pbr/packaging.py", line 705, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "/usr/lib/python3.6/email/__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "/usr/lib/python3.6/email/parser.py", line 54, in parse
        data = fp.read(8192)
      File "/opt/atlassian/pipelines/agent/build/.tox/py36-1.11/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 861: ordinal not in range(128)
    error in setup command: Error parsing /tmp/pip-build-_vhx9u12/django-select2/setup.cfg: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 861: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_vhx9u12/django-select2/
```

On my workstation, it installs fine under both python 2.7 and 3.6.

**Comment by jieter** [comment]
I just managed to fix this by adding this to my `Dockerfile`:
```
ENV LANG=en_US.UTF-8
RUN locale-gen en_US.UTF-8
```

**Comment by 4crash** [comment]
Hi,
I found out that problem is in pip 9.xx , same problem occurs also in other django-packages, 
I had to install pip development version 10:
pip install -U git+https://github.com/pypa/pip
