### ISSUE TITLE
ImportError: No module named 'tasks'

### ISSUE THREAD

**Issue by frague59** [applegrew/django-select2#462]
Hi, 
Upgrading Django-Select2 from 6.0.1 to 6.0.2, I've an error:
```
  Using cached django-select2-6.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/var/www/agenda-pp.tourcoing.fr/virtualenv/lib/python3.4/site-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/var/www/agenda-pp.tourcoing.fr/virtualenv/lib/python3.4/site-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/var/www/agenda-pp.tourcoing.fr/virtualenv/lib/python3.4/site-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/var/www/agenda-pp.tourcoing.fr/virtualenv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2414, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'tasks'
    error in setup command: Error parsing /tmp/pip-build-fvt0mqrc/Django-Select2/setup.cfg: ImportError: No module named 'tasks'

```

This error seem to be related to `pbr`, but I had to (temporary) lock Django-Select2 to 6.0.1.

Have you any idea on how to fix this ? Thanks !
```sh
$ python --version
python 3.4.2
```
```sh
$ ./manage.py --version
1.11.10
```
```sh
$ pip list
asn1crypto (0.24.0)
bleach (2.0.0)
cairocffi (0.7.2)
CairoSVG (2.1.3)
certifi (2018.1.18)
cffi (1.10.0)
chardet (3.0.4)
cli-helpers (1.0.1)
click (6.7)
configobj (5.0.6)
cryptography (2.1.4)
cssselect2 (0.2.1)
defusedxml (0.5.0)
digitick-client (0.1.0a4)
Django (1.11.10)
django-analytical (2.4.0)
django-any-imagefield (0.9)
django-appconf (1.0.2)
django-bleach (0.3.0)
django-bootstrap3 (9.1.0)
django-bootstrap3-datetimepicker-2 (2.5.0)
django-bower (5.2.0)
django-buttons (0.6.0a1)
django-clear-cache (0.3)
django-common-helpers (0.9.1)
django-compressor (2.2)
django-crispy-forms (1.7.0)
django-cron (0.5.0)
django-extensions (1.9.9)
django-filter (1.1.0)
django-flot (1.3.3)
django-fontawesome (0.3.1)
django-form-utils (1.0.3)
django-geojson (2.11.0)
django-grappelli (2.11.1)
django-haystack (2.7.0)
django-haystack-elasticsearch (0.1.0)
django-html5-boilerplate (1.0.8)
django-js-asset (1.0.0)
django-leaflet (0.23.0)
django-meta (1.4.1)
django-mptt (0.9.0)
django-redis (4.8.0)
django-reversion (2.0.13)
django-robots (3.0)
django-select2 (6.0.1)
django-simple-menu (1.2.1)
django-social-share (1.1.2)
django-summernote (0.8.8.6)
django-tables2 (1.19.0)
django-tinymce (2.7.0)
django-watermark (0.1.8)
django-weasyprint (0.5.0)
djangorestframework (3.7.7)
djangorestframework-jsonp (1.0.2)
djangorestframework-recursive (0.1.2)
elasticsearch (2.4.1)
et-xmlfile (1.0.1)
feedparser (5.2.1)
gunicorn (19.7.1)
html5lib (0.999999999)
icalendar (4.0.1)
idna (2.6)
jdcal (1.3)
jsonfield (2.0.2)
lxml (4.1.1)
mycli (1.16.0)
mysqlclient (1.3.12)
odfpy (1.3.6)
olefile (0.44)
openpyxl (2.5.0)
pbr (3.1.1)
pdfrw (0.4)
Pillow (5.0.0)
pip (9.0.1)
pipdeptree (0.10.1)
prompt-toolkit (1.0.15)
pycparser (2.18)
Pygments (2.2.0)
PyLD (0.8.2)
pylibmc (1.5.2)
PyMySQL (0.8.0)
Pyphen (0.9.4)
python-dateutil (2.6.1)
pytz (2018.3)
PyYAML (3.12)
rcssmin (1.0.6)
redis (2.10.6)
requests (2.18.4)
rjsmin (1.0.12)
setuptools (38.5.1)
six (1.11.0)
sorl-thumbnail (12.4.1)
sqlparse (0.2.4)
tablib (0.12.1)
tabulate (0.8.2)
terminaltables (3.1.0)
tinycss2 (0.6.1)
typing (3.6.4)
unicodecsv (0.14.1)
urllib3 (1.22)
wcwidth (0.1.7)
WeasyPrint (0.42.2)
webencodings (0.5.1)
xlrd (1.1.0)
xlwt (1.3.0)
```

**Comment by codingjoe** [comment]
Hi @frague59 this seems to be a pbr error. I would recommend to approach them directly.
