### ISSUE TITLE
Installing v5.11.1 works fine but 6.0.0 and above failing 

### ISSUE THREAD

**Issue by swaterfall** [applegrew/django-select2#473]
I cant seem to install v6+ using `pip install django_select2` I get the error:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 55: ordinal not in range(128)`

However installing versions 5.11.1 and below works fine. I've updated pip and tried a bunch of stuff recommended elsewhere but I cant get it to work. 

Running Python 2.7.10 and latest version of pip.

Any ideas?

Full log:

```
Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/django_select2.egg-info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j5/kjw05wyd5b1_km_19l7v5tfw0000gn/T/pip-install-N8jGUG/django-select2/setup.py", line 7, in <module>
        pbr=True,
      File "/Users/Steven/.virtualenvs/snag/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/Steven/.virtualenvs/snag/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/private/var/folders/j5/kjw05wyd5b1_km_19l7v5tfw0000gn/T/pip-install-N8jGUG/django-select2/.eggs/pbr-4.0.2-py2.7.egg/pbr/pbr_json.py", line 25, in write_pbr_json
        git_dir = git._run_git_functions()
      File "/private/var/folders/j5/kjw05wyd5b1_km_19l7v5tfw0000gn/T/pip-install-N8jGUG/django-select2/.eggs/pbr-4.0.2-py2.7.egg/pbr/git.py", line 131, in _run_git_functions
        if _git_is_installed():
      File "/private/var/folders/j5/kjw05wyd5b1_km_19l7v5tfw0000gn/T/pip-install-N8jGUG/django-select2/.eggs/pbr-4.0.2-py2.7.egg/pbr/git.py", line 83, in _git_is_installed
        _run_shell_command(['git', '--version'])
      File "/private/var/folders/j5/kjw05wyd5b1_km_19l7v5tfw0000gn/T/pip-install-N8jGUG/django-select2/.eggs/pbr-4.0.2-py2.7.egg/pbr/git.py", line 49, in _run_shell_command
        env=newenv)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 55: ordinal not in range(128)
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j5/kjw05wyd5b1_km_19l7v5tfw0000gn/T/pip-install-N8jGUG/django-select2/
```

**Comment by codingjoe** [comment]
Hi that's because we dropped Python 2 support in version 6, see https://github.com/applegrew/django-select2/releases/tag/6.0.0
