### ISSUE TITLE
TypeError: object.__init__() takes no parameters

### ISSUE THREAD

**Issue by hananhafez** [applegrew/django-select2#475]
i use latest version of django_select2  which is 6.0.2 but when i run my django server i got this error 
 super(ModelSelect2Mixin, self).__init__(*args, **defaults)
TypeError: object.__init__() takes no parameters
in forms.py", line 343, in __init 
 super(ModelSelect2Mixin, self).__init__(*args, **defaults)
but when i remove *args, **defaults it works fine 
any ideas ?

**Comment by codingjoe** [comment]
Hi @hananhafez, thanks for reaching out. It looks like you might be using the wrong class or maybe you create your own widget and inherit from the wrong class or not from all of them.

Would you mind pasting the whole stack trace as well as a example where you use select2?

Best Joe

**Comment by hananhafez** [comment]
@codingjoe  here's the full stack trace 
Unhandled exception in thread started by <function wrapper at 0x7f49396e1b90>
Traceback (most recent call last):
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vamos/dozzan_new/dozzanbackend/MainApp/admin.py", line 9, in <module>
    from MainApp.forms import (PartnerAdminForm, PlaylistForm,  PartnerLabelOverlayForm, PartnerCountryForm, PlaylistSongForm,
  File "/home/vamos/dozzan_new/dozzanbackend/MainApp/forms.py", line 18, in <module>
    class PlaylistSongForm(ModelForm):
  File "/home/vamos/dozzan_new/dozzanbackend/MainApp/forms.py", line 39, in PlaylistSongForm
    'placeholder': 'Lookup track by name or id...'
  File "/home/vamos/dozzan_new/dozzanbackend/new_env/src/django-select2/django_select2/forms.py", line 343, in __init__
    super(ModelSelect2Mixin, self).__init__(*args, **kwargs)
TypeError: object.__init__() takes no parameters

thanks in advance

**Comment by codingjoe** [comment]
Please note that we dropped Python 2 support in Version 6. You can use a previous version or grade your stack to Python 3. I would recommend doing the latter.
If you are still experiencing the problem with Python 3, please feel free to reopen the issue.
I am sorry that I can't be of more help.
